import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState, AppThunk } from "../../app/store";
import { authSecondStep, getUser, getLoginUrl } from "./githubApi";

export interface GithubState {
  loginUrl?: string;
  status: "idle" | "loading" | "failed";
}

export const initialState: GithubState = {
  status: "idle",
};

export const getLoginUrlAsync = createAsyncThunk<string, string>(
  "github/getLoginUrl",
  async (state: string) => {
    return getLoginUrl(state);
  }
);



export const githubSlice = createSlice({
  name: "github",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getLoginUrlAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(getLoginUrlAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.loginUrl = action.payload;
      });
  },
});

export const {} = githubSlice.actions;

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectGithubLoginUrl = (state: RootState) => state.github.loginUrl;

export default githubSlice.reducer;
